working version with CompositeRepositoryApplication
ITs fail due to

Caused by: java.lang.NoClassDefFoundError:
org/codehaus/plexus/util/xml/XmlStreamReader
    at org.eclipse.sisu.osgi.connect.PlexusFrameworkConnectServiceFactory.getFramework
(PlexusFrameworkConnectServiceFactory.java:137)
    at org.eclipse.sisu.osgi.connect.PlexusFrameworkConnectServiceFactory.locateClass
(PlexusFrameworkConnectServiceFactory.java:368)
    at org.eclipse.sisu.osgi.connect.PlexusFrameworkConnectServiceFactory.getService
(PlexusFrameworkConnectServiceFactory.java:352)
    at org.eclipse.tycho.p2maven.DefaultProvisioningAgent.getService
(DefaultProvisioningAgent.java:32)
    at org.eclipse.tycho.p2maven.DefaultProvisioningAgent.getService
(DefaultProvisioningAgent.java:52)
    at org.eclipse.equinox.p2.internal.repository.tools.AbstractApplication.getArtifactRepositoryManager
(AbstractApplication.java:119)
    at org.eclipse.equinox.p2.internal.repository.tools.AbstractApplication.finalizeRepositories
(AbstractApplication.java:99)
    at org.eclipse.equinox.p2.internal.repository.tools.CompositeRepositoryApplication.run
(CompositeRepositoryApplication.java:88)
    at io.github.lorenzobettini.p2utils.p2composite.MyMojo.execute
(MyMojo.java:53)